services:
  api:
    build: .
    ports:
      - "5029:8080"
    volumes:
      - "./data:/app/data"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/finance.db
      - JwtSettings__SecretKey=this-is-a-super-secret-key-for-dev-only-32chars